# site settings
title: Capstone
description: > 
  Segmentation and Comparison of Demographics of the neighborhoods in Toronto to guide House Hunting 

# add the full url for the github repository
repo: "https://github.com/evanwill/go-go-ghpages"

# urls
# your gh-pages url: https://username.github.io
url: https://abbyyan3.github.io/
# your repository name: /repository
baseurl: /Capstone

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
